//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Hotel_California.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLIENTE()
        {
            this.TB_RESERVA = new HashSet<TB_RESERVA>();
            this.TB_USUARIO = new HashSet<TB_USUARIO>();
        }
    
        public string COD_CLI { get; set; }
        public string NOM_CLI { get; set; }
        public string APE_CLI { get; set; }
        public int COD_TIPO_DOC { get; set; }
        public string NUM_DOC { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string NUMERO_TARJETA { get; set; }
        public string FEC_VENC { get; set; }
        public string CVV { get; set; }
        public Nullable<int> COD_TIPO_TARJ { get; set; }
    
        public virtual TB_TIPO_DOC TB_TIPO_DOC { get; set; }
        public virtual TB_TIPO_TARJ TB_TIPO_TARJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RESERVA> TB_RESERVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
