//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Hotel_California.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HABITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_HABITACION()
        {
            this.TB_RESERVA = new HashSet<TB_RESERVA>();
        }
    
        public string COD_HAB { get; set; }
        public string NUM_HAB { get; set; }
        public decimal COSTO_HAB { get; set; }
        public int COD_TIPO_HAB { get; set; }
        public int COD_SEDE { get; set; }
        public int COD_EST_HAB { get; set; }
        public string DESC_HAB { get; set; }
    
        public virtual TB_ESTADO_HAB TB_ESTADO_HAB { get; set; }
        public virtual TB_SEDE TB_SEDE { get; set; }
        public virtual TB_TIPO_HAB TB_TIPO_HAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RESERVA> TB_RESERVA { get; set; }
    }
}
