//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Hotel_California.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RESERVA
    {
        public string COD_RES { get; set; }
        public string COD_CLI { get; set; }
        public System.DateTime FEC_CREACION { get; set; }
        public System.DateTime FEC_RESERVA { get; set; }
        public Nullable<System.DateTime> FEC_CANCEL { get; set; }
        public int DIAS_RESERVA { get; set; }
        public string COD_HAB { get; set; }
        public Nullable<int> DIAS_PENAL { get; set; }
        public Nullable<decimal> MONTO_COBRADO { get; set; }
        public Nullable<System.DateTime> FEC_INI { get; set; }
        public Nullable<System.DateTime> FEC_FIN { get; set; }
        public int COD_EST_RES { get; set; }
    
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual TB_ESTADO_RES TB_ESTADO_RES { get; set; }
        public virtual TB_HABITACION TB_HABITACION { get; set; }
        public virtual TB_PENALIDAD TB_PENALIDAD { get; set; }
    }
}
