//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Hotel_California.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public string COD_USU { get; set; }
        public string NOM_USU { get; set; }
        public string CLAVE { get; set; }
        public string EMAIL { get; set; }
        public string COD_CLI { get; set; }
        public string COD_EMP { get; set; }
    
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual TB_EMPLEADO TB_EMPLEADO { get; set; }
    }
}
